# Generated by Django 3.1.1 on 2020-09-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
