# Generated by Django 3.1.1 on 2020-09-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('name',)},
        ),
    ]
