# Generated by Django 3.1.1 on 2020-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200908_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
