# Generated by Django 3.1.1 on 2020-09-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isManager',
            field=models.BooleanField(null=True),
        ),
    ]
