# Generated by Django 3.1.1 on 2020-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200908_0517'),
        ('user', '0002_auto_20200908_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='plants_in_cart', to='plants.Plant'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_placed',
            field=models.ManyToManyField(related_name='order_placed', to='plants.Plant'),
        ),
    ]
