# Generated by Django 3.1.1 on 2020-09-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200908_0517'),
        ('user', '0005_auto_20200910_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='plants_in_cart', to='plants.Plant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='order_placed',
            field=models.ManyToManyField(blank=True, related_name='order_placed', to='plants.Plant'),
        ),
    ]
